package com.vicry.grownepe.model.nepenthes.spesies

import com.vicry.grownepe.model.nepenthes.Nepenthes

object SpeciesData {
    val nepenthes = listOf(
        Nepenthes(
            1,
            "abalata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874967/Nepenthes/article-species/abalata_kaw86g.jpg",
            "Spesies ini disebut abalata dan selama beberapa dekade disebut sebagai spesies alata hingga akhirnya dipisahkan ke spesies tersendiri.",
            "phytoimages.siu.edu - P.B. Pelser & J.F. Barcelona",
            "Media tanam cocopeat cocok untuk nepenthes lowland dengan tambahan bebatuan seperti pumice atau kanuma.",
            "Low Land",
            "Spesies ini hidup di padang rumput berbatu di area terbuka atau habitat semak belukar pada lereng non-ultramafik dekat laut.",
            "0 sampai 50 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/LC_skvfoe.png",
            "Filipina"
        ),
        Nepenthes(
            2,
            "abgracilis ",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874967/Nepenthes/article-species/abgracilis_jzuc2v.jpg",
            "Spesies ini mendapat namanya yang berarti \"berasal dari gracilis\" merujuk ke spesies yang pertama kali ditemukan oleh merrill sebagai spesies nepenthes.",
            "nepenthescp.blogspot.com",
            "spagnum-moss, cocopeat",
            "Low Land sampai Intermediate",
            "habitat berupa bukit submontane berhutan dengan kondisi tanah kemungkinan ultramafik",
            "620 sampai 720 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/NE_tbi32p.png",
            "Filipina"
        ),
        Nepenthes(
            3,
            "adnata ",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874971/Nepenthes/article-species/adnata_zfe4jt.jpg",
            "Nepenthes ini endemik berasal dari Indonesia ditemukan tepatnya di sumatera barat.",
            "alchetron.com",
            "spagnum-moss, cocopeat",
            "Low Land sampai Intermediate",
            "Habitat berupa bebatuan berpasir",
            "600 sampai 1200 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/EN_hp9vpo.png",
            "Sumatera"
        ),
        Nepenthes(
            4,
            "adrianii ",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874971/Nepenthes/article-species/adrianii_yhsijh.jpg",
            "Spesies nepenthes ini dinamai berdasarkan penemunya yaitu adrian seorang observasi dan antusias tanaman nepenthes dari Indonesia.",
            "two-ton.com",
            "spagnum-moss, cocopeat",
            "Intermediate sampai High Land",
            "Tanaman ini hidup epifit ekstrim di hutan pegunungan mulai dari terendah hingga tertinggi",
            "950 sampai 2000 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/NE_tbi32p.png",
            "Jawa"
        ),
        Nepenthes(
            5,
            "aenigma ",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874971/Nepenthes/article-species/aenigma_lq9rcy.jpg",
            "Spesies ini dinamakan aenigma dari nama latin yang berarti \"teka teki\", merujuk kepada ciri ekologis tidak biasa dari taxon spesies ini",
            "phytoimages.siu.edu - Wally Suarez",
            "spagnum-moss, cocopeat",
            "Intermediate",
            "Spesies ini tumbuh di vegetasi hutan bambu yang lebat serta diselingi tanaman rotan dan pandan.",
            "1150 sampai 1250",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/NE_tbi32p.png",
            "Filipina"
        ),
        Nepenthes(
            6,
            "alata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874971/Nepenthes/article-species/alata_x7xerq.jpg",
            "Spesies nepenthes ini ditemukan cukup lama sehingga sudah banyak dimiliki oleh para penghobi tanaman nepenthes.",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Intermediate sampai High Land",
            "Habitat nepenthes alata berupa hutan pegunungan berlumut di kisaran ketinggian 550 meter.",
            "550 sampai 1650",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/LC_skvfoe.png",
            "Filipina"
        ),
        Nepenthes(
            7,
            "alba",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874971/Nepenthes/article-species/alba_s7rlev.jpg",
            "",
            "alchetron.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            8,
            "albomarginata ",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874186/Nepenthes/article-species/albomarginata_k9ikez.jpg",
            "Spesies nepenthes ini memiliki kantung yang mirip dengan gracilis dengan ciri garis berwarna putih di bawah peristome.",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "Habitat spesies ini mulai dari hutan kerangas di dataran rendah, puncak gunung dan hutan berbukit montane menjadi habitat lain dari spesies ini.",
            "0 sampai 1100 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/LC_skvfoe.png",
            "Borneo, Semenanjung Malaysia dan Sumatera"
        ),
        Nepenthes(
            9,
            "alfredoi",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874186/Nepenthes/article-species/alfredoi_lgzmlb.jpg",
            "",
            "phytoimages.siu.edu - Clint Michael Cleofe",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            10,
            "alzapan",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874186/Nepenthes/article-species/alzapan_bdwisg.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            11,
            "ampullaria",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874188/Nepenthes/article-species/ampullaria_mufwfx.jpg",
            "Spesies nepenthes lowland ini sudah banyak dimiliki oleh para penghobi dan koleksi tanaman nepenthes",
            "carousell.com.my",
            "spagnum-moss, cocopeat",
            "Low Land sampai High Land",
            "Hutan rindang lembab, di hutan rawa Kalimantan dan kerangas, di hutan Araucaria Nugini, juga di hutan sekunder, vegetasi mikrofilus terbuka, atau padang rumput rawa",
            "0 sampai 2100 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/LC_skvfoe.png",
            "Borneo, Kepulauan Maluku, Papua Nugini, Semenanjung Malaysia, Sumatera, Singapura dan Thailand"
        ),
        Nepenthes(
            12,
            "andamana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874187/Nepenthes/article-species/andamana_uxtaxt.jpg",
            "",
            "reddit.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            13,
            "angasanensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874187/Nepenthes/article-species/angasanensis_k7fxd4.jpg",
            "",
            "forum.carnivoren.org",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            14,
            "appendiculata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874189/Nepenthes/article-species/appendiculata_c9ap7b.jpg",
            "",
            "neppy.ru",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            15,
            "argentii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874187/Nepenthes/article-species/argentii_sas5pb.jpg",
            "",
            "inaturalist.org",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            16,
            "aristolochioides",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874188/Nepenthes/article-species/aristolochioides_z6xkmm.jpg",
            "nepenthes aristolochioides berasal dari bahasa latin \"oides\" yang berarti \"mirip\" merujuk ke sebuah bunga dari Aristolochia, sebuah genus tumbuhan yang memiliki lebih dari 500 spesies tersebar di seluruh dunia.\n" +
                    "Spesies nepenthes ini memiliki bentuk peristome menyerupai cincin serta leher kantong yang mengembung berbeda dengan kebanyakan tampilan umum nepenthes.\n",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "Pertama kali ditemukan oleh Jebb dan Cheek pada tahun 1997 di gunung Kerinci dan gunung Tujuh pada kepulauan Sumatera Indonesia.Spesies nepenthes endemik ini berada di ketinggian 2000 sampai 2400 meter dari atas permukaan laut. Di alam liar nepenthes ini ditemukan memanjat sebuah semak dan pohon yang dapat dijangkaunya serta ditemukan terbungkus dengan lumut hutan dan nepenthes ini mampu mencapai tinggi 8m.\n",
            "Spesies nepenthes ini membutuhkan suhu di siang hari tidak lebih dari 30°C serta di malam hari 15°C. Membutuhkan kelembapan tinggi 70% - 90% dan hindari media tanam agar tidak tergenang air karena dapat menyebabkan busuk akar. \n",
            "CR - Critical Endangered",
            "Kepulauan Sumatera"
        ),
        Nepenthes(
            17,
            "armin",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874189/Nepenthes/article-species/armin_q2ubpq.jpg",
            "",
            "phytoimages.siu.edu - John Rey Callado",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            18,
            "attenboroughii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874190/Nepenthes/article-species/attenboroughii_hpzyts.jpg",
            "",
            "reddit.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            19,
            "barcelonae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874190/Nepenthes/article-species/barcelonae_lylgct.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            20,
            "beccariana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874189/Nepenthes/article-species/beccariana_wwrhyi.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            21,
            "bellii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874189/Nepenthes/article-species/bellii_w1oskx.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            22,
            "benstonei",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874186/Nepenthes/article-species/benstonei_hcxidi.jpg",
            "",
            "en-academic.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            23,
            "berbulu",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874186/Nepenthes/article-species/berbulu_omhswl.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            24,
            "biak",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874186/Nepenthes/article-species/biak_tpl15z.jpg",
            "",
            "eurekalert.org - Matin Cheek",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            26,
            "bicalcarata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874187/Nepenthes/article-species/bicalcarata_nrjhag.jpg",
            "Spesies nepenthes ini mendapatkan namanya dari ciri unik kantungnya yang memiliki 2 taring. Hal unik dari nepenthes ini karena tendril atau tangkai penghubung kantungnya sebagai sarang bagi spesies semut sebagai perlindungan dari predator maupun semut itu sendiri sebagai nutrisi bagi kantung bicalcarata.",
            "ar.inspiredpencil.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "Hidup di wilayah hutan gambut, juga terkadang di hutan berumput dengan tanah berpasir.",
            "0 sampai 800 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/VU_etgtu1.png",
            "Borneo"
        ),
        Nepenthes(
            27,
            "bokorensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874187/Nepenthes/article-species/bokorensis_l2vxcx.jpg",
            "",
            "researchgate.net - Jennifer C. Daltry",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            28,
            "bongso",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874187/Nepenthes/article-species/bongso_wscv4t.jpg",
            "",
            "scotlandcarnivorous.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            29,
            "boschiana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874188/Nepenthes/article-species/boschiana_eihad2.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            30,
            "bracteosa",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874188/Nepenthes/article-species/bracteosa_huoycg.jpg",
            "",
            "youtube.com - Carlton Carnivores",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            31,
            "burbidgeae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874188/Nepenthes/article-species/burbidgeae_o9abga.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            32,
            "burkei",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874189/Nepenthes/article-species/burkei_xk9zxb.jpg",
            "",
            "phytoimages.siu.edu - Wally Suarez",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            33,
            "cabanae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874189/Nepenthes/article-species/cabanae_h7ty1n.jpg",
            "",
            "news.mongabay.com - Elizabeth Fitt",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            34,
            "campanulata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874190/Nepenthes/article-species/campanulata_klbct2.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            35,
            "ceciliae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874190/Nepenthes/article-species/ceciliae_osymrp.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            36,
            "chang",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874190/Nepenthes/article-species/chang_jp5wfe.jpg",
            "",
            "neppy.ru",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            37,
            "chaniana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874190/Nepenthes/article-species/chaniana_kkukcd.jpg",
            "",
            "scotlandcarnivorous.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            38,
            "cid",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874190/Nepenthes/article-species/cid-not-found_osjyfo.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            39,
            "clipeata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874191/Nepenthes/article-species/clipeata_bghjw4.jpg",
            "",
            "nepenthesdiary.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            40,
            "copelandii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874191/Nepenthes/article-species/copelandii_lbtsba.jpg",
            "",
            "phytoimages.siu.edu - Rufford Small",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            41,
            "cornuta",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874191/Nepenthes/article-species/cornuta_jueegg.jpg",
            "",
            "phytoimages.siu.edu - Wally Suarez",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            42,
            "dactylifera",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874191/Nepenthes/article-species/dactylifera_vuupkd.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            43,
            "danseri",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874191/Nepenthes/article-species/danseri_v2zicl.jpg",
            "",
            "Flickr",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            44,
            "deaniana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874191/Nepenthes/article-species/deaniana_grfwrk.jpg",
            "",
            "flickr.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            45,
            "densiflora",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874192/Nepenthes/article-species/densiflora_sopb5o.jpg",
            "",
            "nepenthesaroundthehouse.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            46,
            "diabolica",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874193/Nepenthes/article-species/diabolica_csj888.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            47,
            "diatas",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874192/Nepenthes/article-species/diatas_rrfwpe.jpg",
            "",
            "carnivorousjourney.com - Alvin Liu",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            48,
            "distillatoria",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874192/Nepenthes/article-species/distillatoria_ja46xj.jpg",
            "",
            "powo.science.kew.org",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            49,
            "domei",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874192/Nepenthes/article-species/domei_xvevrd.jpg",
            "",
            "wikiwand.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            50,
            "dubia",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874192/Nepenthes/article-species/dubia_h5ozr0.jpg",
            "",
            "cpukforum.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            51,
            "edwardsiana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874193/Nepenthes/article-species/edwardsiana_on7kdu.jpg",
            "",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            52,
            "ephippiata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874193/Nepenthes/article-species/ephippiata_hznkeq.jpg",
            "",
            "wistuba.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            53,
            "epiphytica",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874193/Nepenthes/article-species/epiphytica_rmt7pi.jpg",
            "",
            "crossexotics.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            54,
            "erucoides",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874193/Nepenthes/article-species/erucoides_facmdc.jpg",
            "",
            "phytoimages.siu.edu - P.B. Pelser & J.F. Barcelona",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            55,
            "eustachya",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874195/Nepenthes/article-species/eustachya_p6bwnd.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            56,
            "extincta",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874193/Nepenthes/article-species/extincta_i25lfk.jpg",
            "",
            "artsandculture.google.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            57,
            "eymae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874202/Nepenthes/article-species/eymae_mdtybs.jpg",
            "",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            58,
            "faizaliana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874201/Nepenthes/article-species/faizaliana_phudtk.jpg",
            "",
            "flickriver.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            59,
            "flava",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874202/Nepenthes/article-species/flava_ie5bab.jpg",
            "",
            "predatoryplants.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            60,
            "fractiflexa",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874202/Nepenthes/article-species/fractiflexa_kickyg.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            61,
            "fusca",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874204/Nepenthes/article-species/fusca_brsohf.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            62,
            "gantungensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874202/Nepenthes/article-species/gantungensis_znukth.jpg",
            "",
            "reddit.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            63,
            "glabrata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874203/Nepenthes/article-species/glabrata_hh4qdc.jpg",
            "",
            "growcarnivorousplants.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            64,
            "glandulifera",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874203/Nepenthes/article-species/glandulifera_lsbbgt.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            65,
            "graciliflora",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874202/Nepenthes/article-species/graciliflora_ps2y4u.jpg",
            "",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            66,
            "gracilis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874203/Nepenthes/article-species/gracilis_bvseyb.jpg",
            "",
            "commons.wikimedia.org - Vincent Bazile",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            67,
            "gracillima",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874203/Nepenthes/article-species/gracillima_bgxeel.jpg",
            "",
            "wikiwand.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            68,
            "gymnamphora",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874203/Nepenthes/article-species/gymnamphora_sbkzfm.jpg",
            "",
            "fineartamerica.com - Artur Bogacki",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            69,
            "halmahera",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874203/Nepenthes/article-species/halmahera_wh2fh6.jpg",
            "",
            "chienclee.com - Chien C.Lee",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            70,
            "hamata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874204/Nepenthes/article-species/hamata_laiaau.jpg",
            "",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            71,
            "hamiguitanensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874204/Nepenthes/article-species/hamiguitanensis_q3fnmn.jpg",
            "",
            "jacobimages.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            72,
            "harauensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874204/Nepenthes/article-species/harauensis_fyijf2.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            73,
            "hemsleyana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874204/Nepenthes/article-species/hemsleyana_fyyy3c.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            74,
            "hirsuta",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874204/Nepenthes/article-species/hirsuta_iyttbd.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            75,
            "hirtella",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874204/Nepenthes/article-species/hirtella_tfxorq.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            76,
            "hispida",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874205/Nepenthes/article-species/hispida_fd4doj.jpg",
            "",
            "wistuba.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            77,
            "holdenii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874205/Nepenthes/article-species/holdenii_yk5hnn.jpg",
            "",
            "Steve Scalise",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            78,
            "inermis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874205/Nepenthes/article-species/inermis_pkefli.jpg",
            "",
            "omnisterra.com - Andreas Wistuba",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            79,
            "insignis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874205/Nepenthes/article-species/insignis_suydhb.jpg",
            "",
            "alchetron.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            80,
            "izumiae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874205/Nepenthes/article-species/izumiae_k5blur.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            81,
            "jacquelineae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874206/Nepenthes/article-species/jacquelineae_g1xclv.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            82,
            "jamban",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874206/Nepenthes/article-species/jamban_klhuim.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            83,
            "junghuhnii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874206/Nepenthes/article-species/junghuhnii_iglkqc.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            84,
            "justinae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874206/Nepenthes/article-species/justinae_ew1uai.jpg",
            "",
            "phytoimages.siu.edu - John Clifton Martyr",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            85,
            "kampotiana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874206/Nepenthes/article-species/kampotiana_pbrrxl.jpg",
            "",
            "alchetron.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            86,
            "kerrii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874206/Nepenthes/article-species/kerrii_kp076g.jpg",
            "",
            "wikiwand.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            87,
            "khasiana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874206/Nepenthes/article-species/khasiana_nu7gms.jpg",
            "",
            "efloraofindia.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            88,
            "kitanglad",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874207/Nepenthes/article-species/kitanglad_f20w6j.jpg",
            "",
            "inaturalist.ca",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            89,
            "klossii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874213/Nepenthes/article-species/klossii_toqopj.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            90,
            "kongkandana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874213/Nepenthes/article-species/kongkandana_zdqfsu.jpg",
            "",
            "borneoexotics.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            91,
            "krabiensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874213/Nepenthes/article-species/krabiensis_fbz51p.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            92,
            "lamii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874213/Nepenthes/article-species/lamii_dkgwix.jpg",
            "",
            "alchetron.com - Andreas Wistuba",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            93,
            "latiffiana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874213/Nepenthes/article-species/latiffiana_pgusex.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            94,
            "lavicola",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874214/Nepenthes/article-species/lavicola_aa1d1x.jpg",
            "",
            "alchetron.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            95,
            "leonardoi",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874214/Nepenthes/article-species/leonardoi_kygflr.jpg",
            "",
            "phytoimages.siu.edu - Alastair Robinson",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            96,
            "leyte",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874214/Nepenthes/article-species/leyte_mnsjwr.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            97,
            "lingulata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874214/Nepenthes/article-species/lingulata_yasuxg.jpg ",
            "",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            98,
            "longifolia",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874214/Nepenthes/article-species/longifolia_sh8l3k.jpg",
            "",
            "Steve Scalise",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            99,
            "longiptera",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874214/Nepenthes/article-species/longiptera_niqp84.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            100,
            "lowii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874214/Nepenthes/article-species/lowii_v5mjtk.jpg",
            "",
            "mexico.inaturalist.org",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            101,
            "macfarlanei",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874216/Nepenthes/article-species/macfarlanei_icsjxy.jpg",
            "",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            102,
            "macrophylla",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874217/Nepenthes/article-species/macrophylla_rog83y.jpg",
            "",
            "bradsgreenhouse.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            103,
            "macrovulgaris",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874219/Nepenthes/article-species/macrovulgaris_d5gtnn.jpg",
            "",
            "alchetron.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            104,
            "madagascariensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874218/Nepenthes/article-species/madagascariensis_ochrcp.jpg",
            "",
            "blackjungleterrariumsupply.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            105,
            "malayensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874218/Nepenthes/article-species/malayensis_zhyqtm.jpg",
            "",
            "researchgate.net - Tamizi et al.",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            106,
            "malimumuensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874219/Nepenthes/article-species/malimumuensis_u7x5xo.jpg",
            "",
            "phytoimages.siu.edu -  Harold C. Armecin",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            107,
            "manobo",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874219/Nepenthes/article-species/manobo_wxkeac.jpg",
            "",
            "phytoimages.siu.edu - Harold C. Armecin",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            108,
            "mantalingajanensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874232/Nepenthes/article-species/mantalingajanensis_vdagoc.jpg",
            "",
            "phytoimages.siu.edu - Leonardo L. Co ",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            109,
            "mapuluensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874247/Nepenthes/article-species/mapuluensis_mnfmf7.jpg",
            "Spesies nepenthes ini merupakan endemik dari Borneo Indonesia dan memiliki bentuk kantung yang lumayan mirip dengan northiana",
            "reddit.com - r/SavageGarden",
            "spagnum-moss, cocopeat",
            "Intermediate",
            "Habitat nepenthes ini berada di hutan berbukit dengan iklim yang sangat panas sehingga sering terjadi kebakaran yang menjadikan spesies ini mulai terancam punah dialam.",
            "700 sampai 800 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/EN_hp9vpo.png",
            "Borneo"
        ),
        Nepenthes(
            110,
            "maryae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874263/Nepenthes/article-species/maryae_bj2if0.jpg",
            "",
            "alchetron.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            111,
            "masoalensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874338/Nepenthes/article-species/masoalensis_z2slpc.jpg",
            "",
            "drosophyllum.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            112,
            "maxima",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874851/Nepenthes/article-species/maxima_eazd5t.jpg",
            "",
            "carnivorousplantresource.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            113,
            "merrilliana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874851/Nepenthes/article-species/merrilliana_kmyszm.jpg",
            "",
            "phytoimages.siu.edu - Reagan Joseph Villanueva",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            114,
            "micramphora",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874851/Nepenthes/article-species/micramphora_ey8pul.jpg",
            "",
            "phytoimages.siu.edu - Leonardo L. Co",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            115,
            "mikei",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874852/Nepenthes/article-species/mikei_cu0umq.jpg",
            "",
            "predatoryplants.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            116,
            "mindanaoensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874852/Nepenthes/article-species/mindanaoensis_foz4vv.jpg",
            "",
            "phytoimages.siu.edu - Romel Arbolonio",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            117,
            "minima",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874852/Nepenthes/article-species/minima_ct7mxd.jpg",
            "",
            "growcarnivorousplants.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            118,
            "mirabilis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874852/Nepenthes/article-species/mirabilis_rnynz7.jpg",
            "Spesies nepenthes ini mendapatkan namanya yang berarti menakjubkan dimana pada masa eksplorasi di masa lampau tanaman nepenthes ini menarik perhatian para ilmuwan di masa lalu.",
            "phytoimages.siu.edu - Mark Gregory Q. Rule",
            "spagnum-moss, cocopeat",
            "Low Land",
            "Habitat dari nepenthes mirabilis sangat beragam dan berbeda beda setiap kultivar mulai dari substrat basa dan asam, dataran berpasir murni, tanah liat, laterit dan gambut",
            "0 sampai 1500 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/LC_skvfoe.png",
            "Australia, Borneo, Kamboja, Jawa, Kepulauan Maluku, Papua Nugini, Semenanjung Malaysia, Sumatera dan masih banyak lagi"
        ),
        Nepenthes(
            119,
            "misoolensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874852/Nepenthes/article-species/misoolensis_kzryuq.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            120,
            "mollis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874852/Nepenthes/article-species/mollis_om8kyj.jpg",
            "",
            "carnivorousplantsociety.ca",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            121,
            "monticola",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874853/Nepenthes/article-species/monticola_jbze4r.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            122,
            "muluensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874853/Nepenthes/article-species/muluensis_rvb7ws.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            123,
            "murudensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874854/Nepenthes/article-species/murudensis_lsszjp.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            124,
            "naga",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874854/Nepenthes/article-species/naga_igqxka.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            125,
            "nebularum",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874854/Nepenthes/article-species/nebularum_vjhkeu.jpg",
            "",
            "phytoimages.siu.edu - Wally Suarez",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            126,
            "negros",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874854/Nepenthes/article-species/negros_nfo0dh.jpg",
            "",
            "phytoimages.siu.edu - Leonardo L. Co",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            127,
            "neoguineensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874854/Nepenthes/article-species/neoguineensis_rclygl.jpg",
            "",
            "en-academic.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            128,
            "nigra",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874854/Nepenthes/article-species/nigra_hzjcyn.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            129,
            "northiana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874855/Nepenthes/article-species/northiana_u1mqwq.jpg",
            "Spesies nepenthes ini endemik Indonesia, Borneo dan hidup di daerah bebatuan di sarawak",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "Spesies ini hidup di area tebing tebing granit atau limestone dan endemik di wilayah sarawak.",
            "0 sampai 500 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/VU_etgtu1.png",
            "Borneo"
        ),
        Nepenthes(
            130,
            "orbiculata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874854/Nepenthes/article-species/orbiculata_gftg6h.jpg",
            "",
            "nepenthesdiary.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            131,
            "ovata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874854/Nepenthes/article-species/ovata_guekvy.jpg",
            "",
            "alchetron.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            132,
            "palawanensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874855/Nepenthes/article-species/palawanensis_t5hhl1.jpg",
            "",
            "phytoimages.siu.edu - Will Cabanillas",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            133,
            "paniculata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874855/Nepenthes/article-species/paniculata_n06xas.jpg",
            "",
            "Andreas Wistuba",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            134,
            "pantaronensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874855/Nepenthes/article-species/pantaronensis_tfskbc.jpg",
            "",
            "cpphotofinder.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            135,
            "papuana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874855/Nepenthes/article-species/papuana_ncxkk7.jpg",
            "",
            "de-academic.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            136,
            "parvula",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874855/Nepenthes/article-species/parvula_joemoq.jpg",
            "",
            "reddit.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            137,
            "pectinata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874855/Nepenthes/article-species/pectinata_cgreia.jpg",
            "",
            "phytoimages.siu.edu - Wendy A. Mustaqim",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            138,
            "peltata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874855/Nepenthes/article-species/peltata_x02ku2.jpg",
            "",
            "phytoimages.siu.edu -  P.B. Pelser",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            139,
            "pervillei",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874856/Nepenthes/article-species/pervillei_xzemzn.jpg",
            "",
            "ourbreathingplanet.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            140,
            "petiolata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874856/Nepenthes/article-species/petiolata_ubhmng.jpg",
            "",
            "phytoimages.siu.edu - Derek D. Cabactulan",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            141,
            "philippinensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874856/Nepenthes/article-species/philippinensis_lrpjhu.jpg",
            "",
            "phytoimages.siu.edu - P.B. Pelser & J.F. Barcelona",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            142,
            "pilosa",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874856/Nepenthes/article-species/pilosa_zi30df.jpg",
            "",
            "wikiwand.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            143,
            "pitopangii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874856/Nepenthes/article-species/pitopangii_ud3apy.jpg",
            "",
            "wistuba.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            144,
            "platychila",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874856/Nepenthes/article-species/platychila_xhyosz.jpg",
            "",
            "carnivero.com",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            145,
            "pudica",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874857/Nepenthes/article-species/pudica_q3qryo.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            146,
            "pulchra",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874857/Nepenthes/article-species/pulchra_xgfqsv.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            147,
            "putaiguneung",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874857/Nepenthes/article-species/putaiguneung_fpenn9.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            148,
            "rafflesiana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874858/Nepenthes/article-species/rafflesiana_erb3q9.jpg",
            "Spesies nepenthes ini merupakan spesies low land yang gemar dikoleksi para hobi tanaman nepenthes dengan bentuk kantung yang sangat beragam.",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "Persebaran habitat dari spesies rafflesiana sangat beragam dan mampu hidup mulai dari dataran rendah hingga dataran tinggi",
            "0 sampai 1200 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/LC_skvfoe.png",
            "Borneo, Semenanjung Malaysia, Singapura dan Sumatera"
        ),
        Nepenthes(
            149,
            "rajah",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874858/Nepenthes/article-species/rajah_saz1e9.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            150,
            "ramispina",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874857/Nepenthes/article-species/ramispina_eo9ubo.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            151,
            "ramos",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874876/Nepenthes/article-species/ramos_pyc6ib.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            152,
            "reinwardtiana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874892/Nepenthes/article-species/reinwardtiana_kfl372.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            153,
            "rhombicaulis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874908/Nepenthes/article-species/rhombicaulis_mwouzz.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            154,
            "rigidifolia",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874952/Nepenthes/article-species/rigidifolia_erezio.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            155,
            "robcantleyi",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874952/Nepenthes/article-species/robcantleyi_g8tuas.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            156,
            "rosea",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874952/Nepenthes/article-species/rosea_fhem2o.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            157,
            "rowaniae",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874953/Nepenthes/article-species/rowaniae_muczs0.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            158,
            "samar",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874952/Nepenthes/article-species/samar_wf0euo.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            159,
            "sanguinea",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874952/Nepenthes/article-species/sanguinea_susnnn.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            160,
            "saranganiensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874953/Nepenthes/article-species/saranganiensis_snbss0.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            161,
            "sericea",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874953/Nepenthes/article-species/sericea_dpizvf.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            162,
            "sibuyanensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874953/Nepenthes/article-species/sibuyanensis_uqccnp.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            163,
            "singalana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874953/Nepenthes/article-species/singalana_dotwjs.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            164,
            "smilesii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874953/Nepenthes/article-species/smilesii_rhv4ih.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            165,
            "spathulata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874954/Nepenthes/article-species/spathulata_satzmu.jpg",
            "Spesies ini memiliki kemiripan dengan nepenthes Singalana dan beberapa nepenthes Spathulata complex seperti gymnamphora, penctiata, serta adrianii",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "Habitat nepenthes ini di hutan dan lereng terbuka",
            "",
            "",
            ""
        ),
        Nepenthes(
            166,
            "spectabilis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874954/Nepenthes/article-species/spectabilis_xjpp7s.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            167,
            "stenophylla",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874954/Nepenthes/article-species/stenophylla_qmjr1d.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            168,
            "sumagaya",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874959/Nepenthes/article-species/sumagaya_aqbpos.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            169,
            "sumatrana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874958/Nepenthes/article-species/sumatrana_dyvu1i.jpg",
            "Spesies nepenthes ini endemik dari Indonesia dan mulau mengalami penurunan populasi yang drastis. Seusai dengan namanya dengan persebaran di kepulauan sumatera.",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "habitat spesies ini berada di lereng-lereng gunung sehingga komposisi bebatuan sangat disukai oleh spesies ini.",
            "0 sampai 800 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/CR_n3pjca.png",
            "Sumatera"
        ),
        Nepenthes(
            170,
            "suratensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874958/Nepenthes/article-species/suratensis_hpsilh.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            171,
            "surigaoensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874958/Nepenthes/article-species/surigaoensis_ow0yog.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            172,
            "talaandig",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874958/Nepenthes/article-species/talaandig_tbkeyl.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            173,
            "talangensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874958/Nepenthes/article-species/talangensis_jirbsd.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            174,
            "taminii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874959/Nepenthes/article-species/taminii_gals81.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            175,
            "tayninhensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874959/Nepenthes/article-species/tayninhensis_ic23zb.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            176,
            "tboli",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874959/Nepenthes/article-species/tboli_r4e1xz.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            177,
            "tenax",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874959/Nepenthes/article-species/tenax_yccqvb.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            178,
            "tentaculata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874959/Nepenthes/article-species/tentaculata_vnzmhp.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            179,
            "tenuis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874960/Nepenthes/article-species/tenuis_kdljn2.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            180,
            "thai",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874960/Nepenthes/article-species/thai_dgaqsk.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            181,
            "thorelii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874960/Nepenthes/article-species/thorelii_lvzo14.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            182,
            "tobaica",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874960/Nepenthes/article-species/tobaica_l1iyqc.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            183,
            "tomoriana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874963/Nepenthes/article-species/tomoriana_gm5v2p.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            184,
            "treubiana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737379703/Nepenthes/article-species/treubiana_l0xavv.jpg",
            "speseies nepenthes ini juga salah satu endemik Indonesia terutama di kepulauan papua.",
            "carnivero",
            "spagnum-moss, cocopeat",
            "Low Land",
            "Habitat spesies ini di sisi sisi tebing dekat pantai dengan daerah bebatuan serta spesies ini dapat hidup bahkan dengan air di TDS tinggi.",
            "0 sampai 80 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/LC_skvfoe.png",
            "Papua Nugini"
        ),
        Nepenthes(
            185,
            "truncata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874964/Nepenthes/article-species/truncata_tmegbd.jpg",
            "Spesies nepenthes ini mendapatkan namanya yaitu dari bentuk daunnya yang berbentuk hati dengan kantung berukuran besar serta pertumbuhannya sangat lama. Ukuran kantung yang besar dari nepenthes ini mampu mencerna mamalia kecil seperti tikus.",
            "",
            "spagnum-moss, cocopeat",
            "Low Land sampai high land",
            "Habitat nepenthes ini mulai dari dataran pegunungan terbuka hingga epifit di pepohonan dataran tinggi",
            "0 sampai 1500 meter",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1737265210/Nepenthes/IUCN/EN_hp9vpo.png",
            "Filipina"
        ),
        Nepenthes(
            186,
            "ultra",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874964/Nepenthes/article-species/ultra_djmpfw.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            187,
            "ulukaliana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874964/Nepenthes/article-species/ulukaliana_r7i9kj.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            188,
            "undulatifolia",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874964/Nepenthes/article-species/undulatifolia_jk97mh.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            189,
            "veitchii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874964/Nepenthes/article-species/veitchii_bxtizz.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            190,
            "ventricosa",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874965/Nepenthes/article-species/ventricosa_r5puoa.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            191,
            "vieillardii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874965/Nepenthes/article-species/vieillardii_navetk.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            192,
            "villosa",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874965/Nepenthes/article-species/villosa_gf00yp.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            193,
            "viridis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874966/Nepenthes/article-species/viridis_bmmxdg.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            194,
            "vogelii",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874966/Nepenthes/article-species/vogelii_wkdigu.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            195,
            "weda",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874966/Nepenthes/article-species/weda_by0nus.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            196,
            "xiphioides",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874966/Nepenthes/article-species/xiphioides_rjuibn.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            197,
            "zakriana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874966/Nepenthes/article-species/zakriana_gva7gv.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
        Nepenthes(
            198,
            "zygon",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1735874966/Nepenthes/article-species/zygon_vjtzkp.jpg",
            "",
            "",
            "spagnum-moss, cocopeat",
            "Low Land",
            "",
            "",
            "",
            ""
        ),
    )
}