package com.vicry.grownepe.model.nepenthes.naturalhybrid

import com.vicry.grownepe.model.nepenthes.Nepenthes

object NaturalHybridData {
    val nepenthes = listOf(
        Nepenthes(
            1,
            "N. x alisaputrana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721963658/Nepenthes/article-natural-hybrid/AlisaputranaInfo1_flywsc.jpg",
            "Nepenthes Mirabilis adalah salah satu tanaman pitcher yang paling banyak ditanam di dunia. Mudah dibudidayakan, yang membuatnya cocok untuk mereka yang tidak memiliki pengalaman dengan tanaman karnivora.",
            "60%",
            "spagnum-moss",
            "Low Land",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721963658/Nepenthes/article-natural-hybrid/AlisaputranaInfo2_qpsvyu.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721963658/Nepenthes/article-natural-hybrid/Alisaputrana_yjvdgx.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721963657/Nepenthes/article-natural-hybrid/AlisaputranaInfo3_vdr7pc.jpg",
            "",
            "",
            "",
            "N. burbidgeae × N. rajah"
        ),
        Nepenthes(
            2,
            "N. x Hookeriana",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721963913/Nepenthes/article-natural-hybrid/Hookeriana_x3gnba.jpg",
            "Nepenthes Ampullaria adalah detritivor yaitu dapat memakan sisa daun-daunan selain sebagai tanaman karnivora. Tanaman ini juga memiliki beberapa persyaratan perawatan khusus, tetapi tidak ada yang terlalu sulit untuk ditangani oleh pemula.",
            "50%",
            "spagnum-moss, cocopeat",
            "Low Land",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721963913/Nepenthes/article-natural-hybrid/HookerianaInfo1_paazjt.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721963913/Nepenthes/article-natural-hybrid/HookerianaInfo3_sz2eqd.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721963914/Nepenthes/article-natural-hybrid/HookerianaInf21_qvziue.jpg",
            "",
            "",
            "",
            "N. ampullaria × N. rafflesiana"
        ),
        Nepenthes(
            3,
            "N. x Kuchingensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721964195/Nepenthes/article-natural-hybrid/kuchingensisInfo1_er5xkh.jpg",
            "Nepenthes ini banyak ditemukan di negara Asia Tenggara, nepenthes gracilis terkenal karena kendinya yang panjang dan bersemangat. Ini khusus dalam perangkap serangga berwarna hijau atau merah berbintik-bintik, kadang-kadang gelap dan dalam varian lain cerah. N. gracilis adalah nepenthes dataran rendah yang umum dan mudah tumbuh di bawah kondisi yang tepat. Anda dapat menggunakan panduan berikut untuk budidaya.",
            "60%",
            "cocopeat, coco husk",
            "Low Land",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721964194/Nepenthes/article-natural-hybrid/kuchingensis_q1gorf.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721964194/Nepenthes/article-natural-hybrid/kuchingensisInfo2_tgue0b.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721964194/Nepenthes/article-natural-hybrid/kuchingensisInfo3_zh5mm4.jpg",
            "",
            "",
            "",
            "N. ampullaria × N. mirabilis"
        ),
        Nepenthes(
            4,
            "N. × ventrata",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721964602/Nepenthes/article-natural-hybrid/Ventrata_vglw6k.jpg",
            "Nepenthes Rafflesiana adalah tanaman kantong semar dataran rendah yang endemik di seluruh Asia Tenggara. Di alam liar tanaman ini mencapai hingga 50 kaki (15 meter), tetapi yang dijual untuk rumah dan kebun tumbuh pada 4-5 inci yang lebih mudah dikelola (sekitar 8 cm). Dalam panduan mendalam ini Anda akan menemukan cara yang tepat untuk merawat nepenthes ini.",
            "80%",
            "spagnum-moss, cocopeat",
            "Low Land",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721964602/Nepenthes/article-natural-hybrid/Ventrata_vglw6k.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721964603/Nepenthes/article-natural-hybrid/VentrataInfo2_kwqnnz.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721964603/Nepenthes/article-natural-hybrid/VentrataInfo3_zqp09h.jpg",
            "",
            "",
            "",
            "N. alata × N. ventricosa"
        ),
        Nepenthes(
            5,
            "N. × bauensis",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966627/Nepenthes/article-natural-hybrid/Bauensis_dwo4zw.jpg",
            "Nepenthes Rafflesiana adalah tanaman kantong semar dataran rendah yang endemik di seluruh Asia Tenggara. Di alam liar tanaman ini mencapai hingga 50 kaki (15 meter), tetapi yang dijual untuk rumah dan kebun tumbuh pada 4-5 inci yang lebih mudah dikelola (sekitar 8 cm). Dalam panduan mendalam ini Anda akan menemukan cara yang tepat untuk merawat nepenthes ini.",
            "80%",
            "spagnum-moss, cocopeat",
            "Low Land",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966627/Nepenthes/article-natural-hybrid/Bauensis_dwo4zw.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966627/Nepenthes/article-natural-hybrid/BauensisInfo1_nbmo2m.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966627/Nepenthes/article-natural-hybrid/BauensisInfo2_wqxnfl.jpg",
            "",
            "",
            "",
            "N. × bauensis"
        ),
        Nepenthes(
            6,
            "N. × cantleyi",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966961/Nepenthes/article-natural-hybrid/cantleyi_uyaw9p.jpg",
            "Nepenthes Rafflesiana adalah tanaman kantong semar dataran rendah yang endemik di seluruh Asia Tenggara. Di alam liar tanaman ini mencapai hingga 50 kaki (15 meter), tetapi yang dijual untuk rumah dan kebun tumbuh pada 4-5 inci yang lebih mudah dikelola (sekitar 8 cm). Dalam panduan mendalam ini Anda akan menemukan cara yang tepat untuk merawat nepenthes ini.",
            "80%",
            "spagnum-moss, cocopeat",
            "Low Land",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966962/Nepenthes/article-natural-hybrid/cantleyiInfo1_l3teng.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966964/Nepenthes/article-natural-hybrid/cantleyiInfo3_hieu7t.jpg",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966965/Nepenthes/article-natural-hybrid/cantleyiInfo2_tkospv.jpg",
            "",
            "",
            "",
            "N. bicalcarata × N. gracilis"
        ),
        Nepenthes(
            7,
            "N. × cincta",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966966/Nepenthes/article-natural-hybrid/Cincta_n18jeq.jpg",
            "Nepenthes Rafflesiana adalah tanaman kantong semar dataran rendah yang endemik di seluruh Asia Tenggara. Di alam liar tanaman ini mencapai hingga 50 kaki (15 meter), tetapi yang dijual untuk rumah dan kebun tumbuh pada 4-5 inci yang lebih mudah dikelola (sekitar 8 cm). Dalam panduan mendalam ini Anda akan menemukan cara yang tepat untuk merawat nepenthes ini.",
            "80%",
            "spagnum-moss, cocopeat",
            "Low Land",
            "https://res.cloudinary.com/ddmaxq4xx/image/upload/v1721966961/Nepenthes/article-natural-hybrid/CinctaInfo1_vgmrjo.jpg",
            "",
            "",
            "",
            "",
            "",
            "N. albomarginata × N. northiana"
        ),
    )
}